leftnav:
- identifier: 8a35fb4c-d684-8751-0388-aa9e408f3bb8
  name: Front-End Matter
  pageRef: /pages/front-end-matter
  weight: 10
- identifier: 2b76c811-c8fe-b72c-b9c5-e59ddb3ab309
  name: Chapter 1
  pageRef: /pages/chapter-1
  weight: 20
- identifier: a7c7ef8e-f616-e7d9-68be-a8a1ea2367a0
  name: Chapter 2
  pageRef: /pages/chapter-2
  weight: 30
- identifier: be2b9ed4-c1cd-229f-35dd-1ef6592b3d7f
  name: Chapter 3
  pageRef: /pages/chapter-3
  weight: 40
- identifier: c6f23204-4736-5b65-eb90-5a1e7cea2db4
  name: Chapter 4
  pageRef: /pages/chapter-4
  weight: 50
- identifier: 8658f58c-d6e2-d103-e723-926b9acead81
  name: Chapter 5
  pageRef: /pages/chapter-5
  weight: 60
- identifier: 01ee9e71-9c02-84a2-f293-a9b7db5d103d
  name: Chapter 6
  pageRef: /pages/chapter-6
  weight: 70
- identifier: e3c8e3aa-5342-59c7-b03d-e09f2c6ac455
  name: Chapter 7
  pageRef: /pages/chapter-7
  weight: 80
- identifier: f94393b4-1330-86d3-8008-5b748deb6936
  name: Chapter 8
  pageRef: /pages/chapter-8
  weight: 90
- identifier: 5facb331-041b-4305-6eec-0503080cecb4
  name: Chapter 9
  pageRef: /pages/chapter-9
  weight: 100
- identifier: ae221967-6cdf-3f09-1e47-904371b7612f
  name: Chapter 10
  pageRef: /pages/chapter-10
  weight: 110
- identifier: cde42339-1482-7468-dc05-1a2b2abab981
  name: Chapter 11
  pageRef: /pages/chapter-11
  weight: 120
- identifier: c7e4a3ac-7372-0a82-b7df-3fc14bd9134d
  name: Chapter 12
  pageRef: /pages/chapter-12
  weight: 130
- identifier: becb8965-2198-6489-e609-218c2562a25a
  name: Chapter 13
  pageRef: /pages/chapter-13
  weight: 140
- identifier: 595a76d3-2e2b-9799-b028-0ed889cd01f1
  name: Chapter 14
  pageRef: /pages/chapter-14
  weight: 150
- identifier: b507b27a-e00d-8e04-ab27-60202f8906f9
  name: Chapter 15
  pageRef: /pages/chapter-15
  weight: 160
- identifier: 095211ac-3458-3030-9c56-c809018dc6cc
  name: Solutions Manual
  pageRef: /pages/solutions-manual
  weight: 170
